kibot:
  version: 1
  
preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

outputs:
  # STEP (ISO 10303-21 Clear Text Encoding of the Exchange Structure):
  # This is the most common 3D format for exchange purposes.
  # This output is what you get from the 'File/Export/STEP' menu in pcbnew.
  - name: 'https://www.freecadweb.org/'
    comment: '3D step model'
    type: 'step'
    dir: 'cad/3d'
    options:
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: ''
      # [boolean=true] downloads missing 3D models from KiCad git. Only applies to models in KISYS3DMOD
      download: true
      # [string='https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'] base URL for the KiCad 3D models
      kicad_3d_url: 'https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'
      # [boolean=true] use metric units instead of inches
      metric_units: true
      # [number=-1] the minimum distance between points to treat them as separate ones (-1 is KiCad default: 0.01 mm)
      min_distance: -1
      # [boolean=false] used to exclude 3D models for components with 'virtual' attribute
      no_virtual: false
      # [string='grid'] determines the coordinates origin. Using grid the coordinates are the same as you have in the design sheet.
      # The drill option uses the auxiliar reference defined by the user.
      # You can define any other origin using the format 'X,Y', i.e. '3.2,-10'
      origin: 'grid'
      # [string='%f-%i%v.%x'] name for the generated STEP file (%i='3D' %x='step'). Affected by global options
      output: '%f.%x'
      # [string=''] Board variant to apply
      variant: ''