name: test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: make
      - name: show log
        if: ${{ failure() }}
        run: cat build.log
      - name: install
        run: sudo apt-get install -y shunit2
      - name: run tests
        run: make test-ci
